# Form implementation generated from reading ui file 'try.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow1")
        MainWindow.resize(681, 442)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 20, 521, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.gridLayoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        #self.menubar.setGeometry(QtCore.QRect(0, 0, 681, 22))
        self.menubar.setObjectName("menubar")
        self.menuOpt1 = QtWidgets.QMenu(parent=self.menubar)
        self.menuOpt1.setObjectName("menuOpt1")
        self.menuSub1 = QtWidgets.QMenu(parent=self.menuOpt1)
        self.menuSub1.setObjectName("menuSub1")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSub2 = QtGui.QAction(parent=MainWindow)
        self.actionSub2.setObjectName("actionSub2")
        self.actionSubsub1 = QtGui.QAction(parent=MainWindow)
        self.actionSubsub1.setObjectName("actionSubsub1")
        self.actionSubsub2 = QtGui.QAction(parent=MainWindow)
        self.actionSubsub2.setObjectName("actionSubsub2")
        self.actionSubsub3 = QtGui.QAction(parent=MainWindow)
        self.actionSubsub3.setObjectName("actionSubsub3")
        self.menuSub1.addAction(self.actionSubsub1)
        self.menuSub1.addAction(self.actionSubsub2)
        self.menuSub1.addAction(self.actionSubsub3)
        self.menuOpt1.addAction(self.menuSub1.menuAction())
        self.menuOpt1.addAction(self.actionSub2)
        self.menubar.addAction(self.menuOpt1.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Save"))
        self.pushButton_2.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.pushButton.setText(_translate("MainWindow", "Copy"))
        self.pushButton.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.menuOpt1.setTitle(_translate("MainWindow", "Opt1"))
        self.menuSub1.setTitle(_translate("MainWindow", "Sub1"))
        self.actionSub2.setText(_translate("MainWindow", "Sub2"))
        self.actionSubsub1.setText(_translate("MainWindow", "Subsub1"))
        self.actionSubsub2.setText(_translate("MainWindow", "Subsub2"))
        self.actionSubsub3.setText(_translate("MainWindow", "Subsub3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
