# Form implementation generated from reading ui file 'showequations.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys, os

def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")


class Ui_Equation(object):
    def setupUi(self, Equation):
        Equation.setObjectName("Equation")
        Equation.resize(339, 377)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Equation.sizePolicy().hasHeightForWidth())
        Equation.setSizePolicy(sizePolicy)
        Equation.setMinimumSize(QtCore.QSize(339, 377))
        Equation.setMaximumSize(QtCore.QSize(339, 16777215))
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Equation)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 341, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setAutoFillBackground(True)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(resource_path("Equations.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Equation)
        QtCore.QMetaObject.connectSlotsByName(Equation)

    def retranslateUi(self, Equation):
        _translate = QtCore.QCoreApplication.translate
        Equation.setWindowTitle(_translate("Equation", "Equations"))
