# Form implementation generated from reading ui file 'showdata.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import math


class Ui_Table(object):
    def setupUi(self, Table,t,ux,uy,x,y,g):
        Table.setObjectName("Table")
        Table.resize(950, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        Table.setLayout(self.verticalLayout)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DataTable = QtWidgets.QTableWidget()
        self.DataTable.setObjectName("DataTable")
        self.DataTable.setColumnCount(6)
        self.DataTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.DataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.DataTable.setHorizontalHeaderItem(5, item)
        colwidth = [80,160,160,160,160,160]
        for i in range(6):
            self.DataTable.setColumnWidth(i, colwidth[i])
        self.verticalLayout.addWidget(self.DataTable)
        self.buttonBox = QtWidgets.QDialogButtonBox()
        self.buttonBox.setEnabled(True)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedKingdom))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.buttonBox.clicked.connect(Table.reject)

        self.retranslateUi(Table)
        QtCore.QMetaObject.connectSlotsByName(Table)
        self.table(t,ux,uy,x,y,g)

    def retranslateUi(self, Table):
        _translate = QtCore.QCoreApplication.translate
        Table.setWindowTitle(_translate("Table", "Data"))
        item = self.DataTable.horizontalHeaderItem(0)
        item.setText(_translate("Table", "t"))
        item = self.DataTable.horizontalHeaderItem(1)
        item.setText(_translate("Table", "vx"))
        item = self.DataTable.horizontalHeaderItem(2)
        item.setText(_translate("Table", "vy"))
        item = self.DataTable.horizontalHeaderItem(3)
        item.setText(_translate("Table", "v"))
        item = self.DataTable.horizontalHeaderItem(4)
        item.setText(_translate("Table", "x"))
        item = self.DataTable.horizontalHeaderItem(5)
        item.setText(_translate("Table", "y"))
    
    def table(self,t,ux,uy,x,y,g):
        self.DataTable.setRowCount(len(t))
        for row in range(len(t)):
            time = t[row]
            self.DataTable.setItem(row,0,QtWidgets.QTableWidgetItem(str(round(time,2))))
            self.DataTable.setItem(row, 1, QtWidgets.QTableWidgetItem(str(ux)))
            self.DataTable.setItem(row, 2, QtWidgets.QTableWidgetItem(str(uy-g*time)))
            self.DataTable.setItem(row, 3, QtWidgets.QTableWidgetItem(str(math.sqrt(ux**2+(uy-g*time)**2))))
            self.DataTable.setItem(row, 4, QtWidgets.QTableWidgetItem(str(x[row])))
            self.DataTable.setItem(row, 5, QtWidgets.QTableWidgetItem(str(y[row])))
